[phases.setup]
nixPkgs = ['nodejs-20_x', 'nodejs', 'npm']

[phases.install]
cmds = ['cd back-end && npm install']

[phases.build]
cmds = ['cd back-end && npm install']

[start]
cmd = 'cd back-end && npm start' 