[build]
builder = "nixpacks"
buildCommand = "cd back-end && npm install"

[deploy]
startCommand = "cd back-end && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.railway]
name = "nexistaskbot-backend"

[[services]]
name = "mysql"
type = "mysql"
plan = "free"

[[services]]
name = "web"
type = "web"
plan = "free"
env = ["MYSQL_HOST", "MYSQL_DB", "MYSQL_USER", "MYSQL_PASSWORD", "SECRET_KEY", "TELEGRAM_BOT_TOKEN", "ALLOWED_ORIGINS"] 